version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - chat-network
    ports:
      - 27017:27017

networks:
  chat-network:
    name: chat-network
